openapi: 3.0.0
info:
  description: "This is a sample Lab4 server."
  version: "1.0.0"
  title: "Swagger lab4"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "polishkoandrii@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
basePath: "/api/v1"
schemes:
  - "http"
paths:
  /student/create:
    get:
      tags:
        - "student"
      summary: "Create a student"
      description: "Shows form for student creation"
      produces:
        - "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Student"
    post:
      tags:
        - "student"
      summary: "Create a student"
      description: "Create and add a student."
      operationId: "create"
      consumes:
        - "Object"
      produces:
        - "String"
      parameters:
        - name: "student"
          in: "body"
          description: "Student object that needs to be added to the database"
          required: true
          schema:
            $ref: "#/definitions/Student"
      responses:
        "201":
          description: "Successful operation"

  /student/{id}
  get:
    tags:
      - "student"
    summary: "Get a student by the id"
    description: "Shows the student information by their id"
    produces:
      - "string"
    responses:
      "200":
        description: "successful operation"
        schema:
          $ref: "#/definitions/Student"
  put:
    tags:
      - "student"
    summary: "Update student by id"
    description: "Operation to update petition by id"
    operationId: "update"
    produces:
      - "string"
    parameters:
      - name: "id"
        in: "path"
        description: "id of petition to update"
        required: true
        type: "integer"
      - name: "name"
        in: "body"
        description: "Updated student name"
        required: false
      - name: "email"
        in: "body"
        description: "Updated student email"
        required: false
        schema:
          $ref: "#/definitions/Student"
    responses:
      "201":
        description: "Petition was successfully created"
  delete:
    tags:
      - "student"
    summary: "Delete the student by the i"
    description: "Delete the student by the id"
    operationId: "delete"
    produces:
      - "string"
    parameters:
      - name: "id"
        in: "path"
        description: "The id of student that needs to be deleted"
        required: true
        type: "integer"
    responses:
      "200":
        description: "Deleted successfully"
definitions:
  Student:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      Name:
        type: "string"
      Email:
        type: "string"
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/AndriiPolishko/Lab4/1.0.0